import asyncio
from copy import deepcopy
import hashlib
import io
import json
import os
from pathlib import Path
import subprocess
import sys
import tarfile
import threading

import pytest

from pantheon.models.group_creation import topology_for
from pantheon.models.group_package import GroupPackageStore, encoded, LEGACY_SOURCE_FILES
from pantheon.apps.lifecycle import build_artifact
from test_model_engines import load
from test_model_snapshots import bundle, snapshots, artifacts
from test_model_sglang_group import plan


@pytest.fixture
def prepared(tmp_path):
    source = bundle(tmp_path)
    snapshots.SnapshotCache(tmp_path, artifacts).fetch(source, threading.Event(), lambda *args: None)
    record = snapshots.snapshot(tmp_path, source['sha256'])
    value = plan()
    value['model_sha256'] = record['sha256']
    for member in value['members']:
        member['generation'] = 2
    return record, value


def creation(store, prepared):
    record, value = prepared
    return dict(protocol=1, owner=value['owner'], group_id=value['group_id'], revision=3,
        plan=value, topology=topology_for(value).document(), source_sha256=store.capture(record),
        phase='building', authority_requested=True, ca_sha256='c'*64,
        authority_closed=False, artifacts=[])


def unpack(payload):
    with tarfile.open(fileobj=io.BytesIO(payload), mode='r:') as archive:
        entries = archive.getmembers()
        assert all(entry.isfile() and entry.mode == 0o400 and entry.mtime == 0 for entry in entries)
        return {entry.name: archive.extractfile(entry).read() for entry in entries}


@pytest.mark.asyncio
async def test_real_snapshot_builds_reproducible_rank_packages_without_weights(tmp_path, prepared):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    first, second = await asyncio.gather(store(row, 0), store(row, 1))
    assert first != second
    assert await GroupPackageStore(store.root)(row, 0) == first
    payload = store.artifact(first)
    files = unpack(payload)
    manifest = json.loads(files['fleet.json'])
    component = manifest['components'][0]
    assert manifest['requires']['caps'] == ['proc', 'model-group-private-network']
    assert component['group_peer'] and component['group_network'] and component['run_as_owner']
    assert component['resources'] == row['plan']['members'][0]['resources']
    assert component['read_only_mounts']['cache/snapshots/' + row['plan']['model_sha256']] == '/fleet/weights'
    assert manifest['dependencies']['container_engine']['provision'] == 'never'
    assert '@sha256:' in component['image'] and 'hooks' not in manifest
    assert json.loads(files['group-peer.json']) == dict(protocol=1, rank=0,
        topology=row['topology'], ca_sha256=row['ca_sha256'])
    assert json.loads(files['group-plan.json']) == row['plan']
    assert json.loads(files['group-build.json']) == dict(protocol=1, source_sha256=row['source_sha256'], rank=0)
    assert not any(name.endswith(('.safetensors', '.pem', '.key')) for name in files)
    assert 'mtime_ns' not in files['group-model.json'].decode()
    assert len(payload) < 512 << 10
    # Generated bytes use Fleet's real canonical artifact format exactly.
    root = tmp_path / 'unpacked'; root.mkdir()
    for name, data in files.items():
        (root / name).write_bytes(data)
    assert build_artifact(root) == (payload, first)
    assert not list(store.root.glob('.building-*'))
    assert not list(store.root.glob('.writing-*'))
    # Optional receipt consumed by the Go admission boundary test.
    if output := os.environ.get('PANTHEON_GROUP_PACKAGE_OUTPUT'):
        Path(output).write_bytes(payload)


@pytest.mark.asyncio
async def test_saved_source_survives_code_changes_and_missing_input_has_no_fallback(tmp_path, prepared, monkeypatch):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    sha = await store(row, 0)
    # Reconstruct with no access to current capture code. Build must use only
    # the original saved compiler and programs, not import updated App modules.
    monkeypatch.setattr(GroupPackageStore, 'capture', lambda *args: pytest.fail('current source consulted'))
    assert await GroupPackageStore(store.root)(row, 0) == sha
    source = store.path('source', row['source_sha256'])
    original = source.read_bytes()
    source.chmod(0o600); source.write_bytes(b'{}')
    with pytest.raises(ValueError, match='corrupt'):
        await store(row, 0)
    source.unlink()
    with pytest.raises(ValueError, match='missing'):
        await store(row, 0)
    assert store.put('source', original) == row['source_sha256']
    assert await store(row, 0) == sha


@pytest.mark.asyncio
async def test_frozen_package_has_all_leader_runtime_dependencies(tmp_path, prepared):
    prepared[1].update(inference_protocol=1, underlay=['192.168.20.10:18441', '192.168.20.11:18441'])
    for member in prepared[1]['members']:
        member['interface'] = 'wg0'
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    files = unpack(store.artifact(await store(row, 0)))
    directory = tmp_path / 'isolated'; directory.mkdir()
    for name, content in files.items():
        (directory / name).write_bytes(content)
    script = '''
import json, sys
from pathlib import Path
from types import SimpleNamespace
from urllib.request import Request, urlopen
sys.path.insert(0, sys.argv[1])
import sglang_group_runtime, group_connector
root = Path(sys.argv[1])
plan = json.loads((root / 'group-plan.json').read_bytes())
record = json.loads((root / 'group-model.json').read_bytes())
identity = dict(instance_id='a'*32, generation=plan['members'][0]['generation'])
token = 'original-owner-credential'
connector = group_connector.GroupConnector(root / 'state', SimpleNamespace(ready=lambda: True), plan, record, identity, token)
server, thread = group_connector.serve(connector, 0)
try:
    origin = f'http://127.0.0.1:{server.server_port}'
    request = Request(origin + '/ready', headers={'X-Pantheon-App-Token': token})
    with urlopen(request, timeout=2) as response:
        assert json.load(response) == dict(protocol=1, ready=True, **identity)
    request = Request(origin + '/rpc', data=json.dumps(dict(method='resume', args={'config_revision': connector.revision})).encode(),
        headers={'X-Fleet-RPC-Token': token})
    with urlopen(request, timeout=2) as response:
        assert json.load(response)['accepting'] is True
    assert connector.discover()['models'][0]['id'] == 'fleet-snapshot-' + record['sha256']
finally:
    server.shutdown(); server.server_close(); thread.join(2)
    connector.activity.db.close()
assert not thread.is_alive()
print('PACKAGED_LEADER_OK')
'''
    result = await asyncio.to_thread(subprocess.run, [sys.executable, '-I', '-c', script, str(directory)],
        cwd=directory, capture_output=True, text=True, timeout=10,
        env={'PATH': os.defpath, 'PYTHONDONTWRITEBYTECODE': '1'})
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == 'PACKAGED_LEADER_OK'


@pytest.mark.asyncio
async def test_legacy_frozen_source_rebuilds_without_new_connector_sources(tmp_path, prepared):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    source = json.loads(store.read('source', row['source_sha256']))
    source['files'] = {name: source['files'][name] for name in LEGACY_SOURCE_FILES}
    # A saved pre-connector compiler has exactly the original runtime file list.
    compiler = source['files']['group_packager.py']
    start, end = compiler.index('RUNTIME_FILES = '), compiler.index('\nSOURCE_FILES = ')
    compiler = compiler[:start] + 'RUNTIME_FILES = ' + repr(tuple(
        n for n in LEGACY_SOURCE_FILES if n != 'group_packager.py')) + compiler[end:]
    source['files']['group_packager.py'] = compiler
    source['files']['sglang_group_runtime.py'] = '# Original status-only entrypoint fixture\n'
    row['source_sha256'] = store.put('source', encoded(source))
    original = await store(row, 0)
    files = unpack(store.artifact(original))
    assert 'group_connector.py' not in files and 'server.py' not in files
    assert files['sglang_group_runtime.py'] == source['files']['sglang_group_runtime.py'].encode()
    assert await GroupPackageStore(store.root)(row, 0) == original


@pytest.mark.asyncio
@pytest.mark.parametrize('change', ['model', 'memory', 'gpu', 'topology', 'rank', 'cancel', 'unclaimed', 'recipe'])
async def test_invalid_group_fails_before_artifact_is_published(tmp_path, prepared, change):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    rank = 0
    if change == 'model': row['plan']['model_sha256'] = 'f'*64
    elif change == 'memory': row['plan']['members'][1]['resources']['memory_bytes'] = 256 << 20
    elif change == 'gpu': row['plan']['members'][1]['physical_gpu_bytes'] = [1 << 30]
    elif change == 'recipe': row['plan']['recipe_id'] = 'untrusted-engine'
    elif change == 'rank': rank = True
    elif change == 'cancel': row['phase'] = 'aborting'
    elif change == 'unclaimed': row['authority_requested'] = False
    row['topology'] = topology_for(row['plan']).document()
    if change == 'topology': row['topology']['launch_sha256'] = 'f'*64
    with pytest.raises((ValueError, RuntimeError)):
        await store(row, rank)
    assert not list(store.root.glob('artifact-*'))
    assert not list(store.root.glob('.building-*'))


@pytest.mark.asyncio
async def test_source_version_and_rank_and_ca_are_in_artifact_identity(tmp_path, prepared):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    original = await store(row, 0)
    changed = deepcopy(row); changed['ca_sha256'] = 'd'*64
    assert await store(changed, 0) != original
    source = json.loads(store.read('source', row['source_sha256']))
    source['files']['group_packager.py'] += '\n# next compiler version\n'
    changed = deepcopy(row); changed['source_sha256'] = store.put('source', encoded(source))
    assert await store(changed, 0) != original
    assert await store(row, 0) == original


@pytest.mark.asyncio
async def test_compiler_timeout_kills_child_and_removes_partial_build(tmp_path, prepared):
    store = GroupPackageStore(tmp_path / 'packages', timeout=.2)
    row = creation(store, prepared)
    source = json.loads(store.read('source', row['source_sha256']))
    source['files']['group_packager.py'] = 'import time\ntime.sleep(60)\n'
    row['source_sha256'] = store.put('source', encoded(source))
    with pytest.raises(TimeoutError):
        await store(row, 0)
    assert not list(store.root.glob('.building-*')) and not list(store.root.glob('artifact-*'))


@pytest.mark.asyncio
async def test_cancel_reaps_real_compiler_before_removing_its_inputs(tmp_path, prepared, monkeypatch):
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    source = json.loads(store.read('source', row['source_sha256']))
    source['files']['group_packager.py'] = 'import time\ntime.sleep(60)\n'
    row['source_sha256'] = store.put('source', encoded(source))
    original, spawned, processes = asyncio.create_subprocess_exec, asyncio.Event(), []

    async def launch(*args, **kwargs):
        child = await original(*args, **kwargs)
        processes.append(child)
        spawned.set()
        return child

    monkeypatch.setattr(asyncio, 'create_subprocess_exec', launch)
    task = asyncio.create_task(store(row, 0))
    try:
        await asyncio.wait_for(spawned.wait(), 2)
    finally:
        task.cancel()
        with pytest.raises(asyncio.CancelledError):
            await task
    assert len(processes) == 1 and processes[0].returncode is not None
    assert not list(store.root.glob('.building-*')) and not list(store.root.glob('artifact-*'))


def test_receipt_is_stable_across_node_metadata_but_pins_files_and_architecture(prepared):
    module = load('group_model')
    record, _ = prepared
    expected = module.descriptor(record)
    changed = deepcopy(record)
    for item in changed['files']:
        item['mtime_ns'] += 1000
    changed['name'], changed['revision'] = 'same-bundle-on-another-node', 'display-only'
    changed['files'].reverse()
    module.check_record(changed, expected)
    for field in ('hash', 'size', 'architecture', 'weights', 'path'):
        changed = deepcopy(record)
        if field == 'hash': changed['files'][0]['sha256'] = 'f'*64
        elif field == 'size': changed['files'][0]['size'] += 1
        elif field == 'architecture': changed['config']['num_hidden_layers'] += 1
        elif field == 'weights': changed['tensor_parallel_weights']['2'] += 1
        elif field == 'path': changed['files'][0]['path'] = '../config.json'
        with pytest.raises(ValueError):
            module.check_record(changed, expected)


def test_node_file_verification_handles_timestamp_rounding_but_rejects_corruption(tmp_path, prepared):
    module = load('group_model')
    record, _ = prepared
    root = tmp_path / 'snapshots' / record['sha256']
    module.check_files(root, record)
    item = next(f for f in record['files'] if f['path'].endswith('.safetensors'))
    path = root / item['path']
    original = path.read_bytes()
    # Image-like metadata drift keeps the exact same verified model bytes.
    os.utime(path, ns=(item['mtime_ns'] + 1000, item['mtime_ns'] + 1000))
    module.check_files(root, record)
    assert item['mtime_ns'] != path.stat().st_mtime_ns
    path.chmod(0o600)
    path.write_bytes(b'x' * len(original))
    with pytest.raises(ValueError, match='content verification'):
        module.check_files(root, record)
    path.unlink(); path.symlink_to(tmp_path / 'blobs' / record['sha256'])
    with pytest.raises((ValueError, OSError)):
        module.check_files(root, record)


def test_store_never_follows_links_or_overwrites_corrupt_cached_bytes(tmp_path):
    store = GroupPackageStore(tmp_path / 'packages')
    sha = store.put('source', b'{"fixture":true}')
    target = store.path('source', sha)
    outside = tmp_path / 'outside'; outside.write_bytes(target.read_bytes())
    target.unlink(); target.symlink_to(outside)
    with pytest.raises((ValueError, OSError)):
        store.read('source', sha)
    with pytest.raises((ValueError, OSError)):
        store.put('source', outside.read_bytes())
    assert outside.read_bytes() == b'{"fixture":true}'
    with pytest.raises(ValueError):
        store.path('source', '../escape')


@pytest.mark.asyncio
async def test_underlay_bound_packages_stage_original_bytes_and_never_rebuild(tmp_path, prepared, monkeypatch):
    from types import SimpleNamespace
    from unittest.mock import AsyncMock
    import base64
    from pantheon.apps.lifecycle import FleetLifecycle, CHUNK_SIZE
    prepared[1]['underlay'] = ['192.168.20.10:18441', '192.168.20.11:18441']
    for member in prepared[1]['members']:
        member['interface'] = 'wg0'
    store = GroupPackageStore(tmp_path / 'packages')
    row = creation(store, prepared)
    for rank in range(2):
        row['artifacts'].append(dict(rank=rank, digest=await store(row, rank)))
    row['phase'] = 'built'
    payload = store.artifact(row['artifacts'][0]['digest'])
    assert json.loads(unpack(payload)['group-plan.json'])['underlay'] == prepared[1]['underlay']
    client = SimpleNamespace(lifecycle=AsyncMock(return_value={}))
    lifecycle = FleetLifecycle(None)
    monkeypatch.setattr(lifecycle, '_client', AsyncMock(return_value=client))
    actual = await store.stage(lifecycle, row, 0)
    sent = [c for c in client.lifecycle.await_args_list if c.args[1] == 'stage']
    assert b''.join(base64.b64decode(c.kwargs['data']) for c in sent) == payload
    assert [c.kwargs['offset'] for c in sent] == list(range(0, len(payload), CHUNK_SIZE))
    assert all(c.args[0] == row['plan']['members'][0]['node_id'] and c.kwargs['digest'] == actual for c in sent)
    assert {c.args[1] for c in client.lifecycle.await_args_list} == {'status', 'stage'}
    client.lifecycle.reset_mock()
    client.lifecycle.return_value = {'installations': {actual: {'state': 'installed'}}}
    assert await store.stage(lifecycle, row, 0) == actual
    assert client.lifecycle.await_count == 1
    store.path('artifact', actual).unlink()
    with pytest.raises(ValueError, match='missing'):
        await store.stage(lifecycle, row, 0)
    assert client.lifecycle.await_count == 1
