/**
 * Cytoscape.js LiveView adapter — biological networks & pathways.
 *
 * Cytoscape.js is the standard JavaScript library for interactive network
 * visualisation: nodes + edges as JSON elements, built-in layout algorithms
 * (cose, breadthfirst, circle, dagre, ...), CSS-like stylesheet by selectors.
 *
 * LiveView "state":
 *   {
 *     "elements": [
 *       { "data": { "id": "geneA", "label": "GeneA" } },
 *       { "data": { "id": "geneB", "label": "GeneB" } },
 *       { "data": { "id": "e1", "source": "geneA", "target": "geneB" } }
 *     ],
 *     "layout":  { "name": "cose", "animate": false },   // optional
 *     "style":   [ ... cytoscape stylesheet array ... ]  // optional
 *   }
 */
import cytoscape from 'https://esm.sh/cytoscape@3.30.0'

// A neutral default stylesheet — readable on a light background, gives the
// agent a working view even with no `style` set.
const DEFAULT_STYLE = [
  { selector: 'node', style: {
      label: 'data(label)',
      'background-color': '#58a6ff',
      color: '#222',
      'font-size': '11px',
      'text-valign': 'center',
      'text-halign': 'center',
      width: 36, height: 36,
  } },
  { selector: 'edge', style: {
      'line-color': '#aaa',
      width: 1.5,
      'curve-style': 'bezier',
      'target-arrow-shape': 'triangle',
      'target-arrow-color': '#aaa',
  } },
]

async function __viewerSetup(lv, root) {
  root.style.width = '100%'
  root.style.height = '100%'
  // WHITE in both themes, deliberately. This viewer draws fixed dark ink —
  // black labels, dark edges — that the package does not control, so a
  // ground that followed the appearance setting would be unreadable in
  // dark. It is paper, and paper is white. An app whose ink it DOES
  // control should use var(--app-bg) instead (docs/app-spec.md).
  root.style.background = '#ffffff'
  root.style.color = '#222'

  let cy = null
  let lastKey = null

  function applyState(state) {
    if (!state || !Array.isArray(state.elements)) {
      lv.fail('Cytoscape: state must include an `elements` array '
        + '(nodes + edges in Cytoscape JSON).')
      return
    }
    const key = JSON.stringify([state.elements, state.layout, state.style])
    if (cy && key === lastKey) return
    lastKey = key

    // Tear down previous instance — Cytoscape doesn't auto-rebuild on
    // wholesale element changes; cleaner to destroy + recreate.
    if (cy) { try { cy.destroy() } catch (_) {} cy = null }
    root.innerHTML = ''
    // Note: `wheelSensitivity` would be nice (slower wheel-zoom) but
    // Cytoscape now console.warns on it as a deprecated/non-standard
    // option, which feeds the LiveView diagnostics channel as noise.
    cy = cytoscape({
      container: root,
      elements: state.elements,
      layout: state.layout || { name: 'cose', animate: false },
      style: state.style || DEFAULT_STYLE,
    })
  }

  lv.onState((state, info) => {
    if (info && info.reason === 'emit') return
    try { applyState(state) }
    catch (e) { lv.fail('Cytoscape: ' + ((e && e.message) || e)) }
  })

  // Cytoscape has its own PNG exporter — it understands its canvas and
  // scales cleanly, better than html2canvas.
  lv.onSnapshot(() => {
    if (!cy) return null
    try {
      return cy.png({ output: 'base64uri', scale: 1.5, full: true, bg: '#ffffff' })
    } catch (_) { return null }
  })
}


// ── file-open shim (generated by convert-viewers.py) ─────────────────────────
// The desktop opens files with generic state {url, path, name, type}; the
// viewer's own contract is documented at the top of this file. File-shaped
// state (a `path`, none of the viewer's keys) is mapped before the stock
// adapter sees it; everything else — agent states, demos — passes through.
const __FILE_KEYS = ["elements"]
// What the desktop itself puts in a file-open state; everything else in it
// came from the caller and is theirs to keep.
const __FILE_STATE_KEYS = ['url', 'path', 'name', 'type']
async function __fromFile(state) {
  const res = await fetch(state.url)
  if (!res.ok) throw new Error('fetch failed: ' + res.status)
  const data = await res.json()
  let elements = null
  if (Array.isArray(data)) elements = data
  else if (Array.isArray(data.elements)) elements = data.elements
  else if (data.elements && (data.elements.nodes || data.elements.edges)) {
    elements = [].concat(data.elements.nodes || [], data.elements.edges || [])
  }
  if (!elements) throw new Error('not a Cytoscape.js elements JSON')
  const out = { elements }
  if (data.layout && data.layout.name) out.layout = data.layout
  if (Array.isArray(data.style)) out.style = data.style
  return out
}
export async function setup(lv, root) {
  const __cbs = []
  let __lastFile = null
  let __cur = null
  const wrapped = Object.create(lv)
  // Adapters read lv.state on their own re-renders (Vitessce does on window
  // resize). The SDK's store still holds the RAW state — file-shaped, or
  // stale after menu-driven changes that bypass it — so point the accessor
  // at what the adapter actually saw last.
  Object.defineProperty(wrapped, 'state', { get: () => __cur })
  wrapped.onState = (cb) => {
    __cbs.push(cb)
    lv.onState((state, info) => {
      // A file open is a file open. This used to also require that the state
      // carried NONE of the viewer's own keys — but those keys are exactly
      // what this app declares as `sync` state, so the first time anyone
      // toggled a mode or picked a colour the window could never run its
      // backend `prepare` again. It then fed the raw file envelope to the
      // viewer: spatial3d fetched `_spatial.json` from inside an .h5ad (404),
      // Vitessce reported "Missing version" on an object that was never a
      // config. The mapping is also what re-mints served URLs, so skipping it
      // left those windows pointing at a dead tunnel after every restart.
      const fileShaped = !!(state && state.path && state.url)
      if (!fileShaped) { __cur = state; cb(state, info); return }
      __lastFile = state
      Promise.resolve(__fromFile(state, lv)).then((mapped) => {
        // Anything the caller asked for beyond the file itself — a layout, a
        // colour scheme, desktop_open(path=…, state={…}) — must survive the
        // mapping. Dropping it silently is why "open it radial" came out
        // linear and sent an agent hunting for a bug that was ours.
        // __FILE_KEYS belong to the FILE: they are what the mapping produces,
        // and they carry served URLs only the current pod can mint. Anything
        // else in the state — a layout, a camera, a colour scheme — is the
        // caller's or the session's, and rides on top.
        const extra = {}
        for (const k of Object.keys(state)) {
          if (!__FILE_STATE_KEYS.includes(k) && !__FILE_KEYS.includes(k)) extra[k] = state[k]
        }
        __emitToApp(Object.assign({}, mapped, extra), info)
      }).catch((e) =>
        lv.fail('Could not open ' + (state.name || state.path) + ': ' + ((e && e.message) || e)))
    })
  }
  // Every shim delivery goes through here — and through the SDK's own store.
  // Adapters build their next state from lv.state (mode toggles, sliders); a
  // delivery that bypassed the store left it holding the bare init `{}`, and
  // the first toolbar click re-rendered from nothing ("Provide state.url").
  const __emitToApp = (state, info) => {
    __cur = state
    if (typeof lv.setState === 'function') lv.setState(state)
    for (const cb of __cbs) cb(state, info || { reason: 'set' })
  }
  // Menu actions patch the CURRENT viewer state — the adapter re-renders the
  // way it would for any set.
  const __patch = (p) => {
    if (!__cur) throw new Error('nothing is loaded yet')
    __emitToApp(Object.assign({}, __cur, p))
  }
  void __patch
  if (typeof lv.defineAction === 'function') {
    lv.defineAction('setLayout', (a) => {
      __patch({ layout: { name: (a && a.name) || 'cose', animate: false } }); return 'ok'
    })
  }
  return __viewerSetup(wrapped, root)
}
