/**
 * Vitessce LiveView adapter — a viewer plugin.
 *
 * This is NOT built into the app. It is an ordinary LiveView component
 * module (the same kind an agent generates): it exports `setup(lv, root)`
 * and is loaded by the generic host `app-host.html`. The only built-in
 * piece of LiveView is the SDK runtime (live-view-sdk.js + app-host.html);
 * every viewer — Vitessce included — is a pluggable module that lives next
 * to its skill file.
 *
 * What it does: (1) load Vitessce, (2) render <Vitessce> with whatever
 * state the SDK hands it, (3) emit Vitessce's state back out. For Vitessce
 * the LiveView "state" IS the Vitessce view config; an agent patch
 * deep-merges into it (e.g. {coordinationSpace:{spatialZoom:{A:5}}}).
 *
 * React resolves via app-host's import map; Vitessce is imported by full
 * URL from unpkg (its genuine browser ESM build). No build step.
 */
import React from 'react'
import { createRoot } from 'react-dom/client'
import { Vitessce } from 'https://unpkg.com/vitessce@latest'

function __viewerSetup(lv, root) {
  let reactRoot = null
  // While we apply agent-driven state, Vitessce's onConfigChange fires for
  // our own write — suppress it so it isn't echoed back as a user edit.
  let applyingRemote = false

  let errorCheckTimer = null
  // The uid is what tells Vitessce "this is a new config" (→ re-initialise &
  // re-fetch). We bump it only on a real state change, NEVER on a resize.
  let currentUid = null

  // Vitessce reports an invalid config NOT by throwing or logging — it just
  // renders a <Warning> ("Config validation failed on second pass." etc.).
  // Nothing else would notice, so status would wrongly stay "ready". Detect
  // that rendered warning and surface it as a hard failure to the agent.
  function checkForVitessceError() {
    const text = (root.textContent || '').trim()
    if (/Config (validation|initialization) failed/i.test(text)) {
      lv.fail('Vitessce rejected the config — ' + text.slice(0, 600))
    }
  }

  function renderVitessce(config, bumpUid) {
    if (!config) return
    if (!reactRoot) reactRoot = createRoot(root)
    // Fresh uid only on a real config change (patch/set) so Vitessce detects it.
    // A resize REUSES the uid — a new uid would make Vitessce re-initialise and
    // re-fetch all data, which is the "reloads on window resize" bug.
    if (bumpUid || !currentUid) currentUid = `lv-${Date.now()}`
    const cfg = { ...config, uid: currentUid }
    reactRoot.render(
      React.createElement(Vitessce, {
        config: cfg,
        theme: 'dark',
        height: window.innerHeight,
        onConfigChange: (newConfig) => {
          if (applyingRemote) return      // our own write — don't echo
          lv.emitState(newConfig)         // user interaction → report out
        },
      }),
    )
    // Config validation runs synchronously on render; check shortly after.
    if (errorCheckTimer) clearTimeout(errorCheckTimer)
    errorCheckTimer = setTimeout(checkForVitessceError, 2500)
  }

  // The LiveView "state" is the Vitessce view config. init/patch/set arrive
  // here as the full merged config. `reason === 'emit'` is our own outgoing
  // change — Vitessce already rendered it, so skip the re-render.
  lv.onState((config, info) => {
    if (info && info.reason === 'emit') return
    applyingRemote = true
    try {
      renderVitessce(config, true)   // real state change → new uid
    } finally {
      // release after the render settles (Vitessce's onConfigChange for
      // our write fires on the next tick)
      setTimeout(() => { applyingRemote = false }, 0)
    }
  })

  // Re-render on resize so Vitessce re-lays-out for the new height — debounced,
  // and with the SAME uid so it does NOT re-fetch data.
  let resizeTimer = null
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer)
    resizeTimer = setTimeout(() => { if (lv.state) renderVitessce(lv.state, false) }, 200)
  })

  // app-host calls lv.ready() once setup() resolves.
}


// ── file-open shim (generated by convert-viewers.py) ─────────────────────────
// The desktop opens files with generic state {url, path, name, type}; the
// viewer's own contract is documented at the top of this file. File-shaped
// state (a `path`, none of the viewer's keys) is mapped before the stock
// adapter sees it; everything else — agent states, demos — passes through.
// The keys the file mapping OWNS — everything `prepare` puts in the config.
// For this viewer that is the whole config, and it has to be, because these
// keys are internally consistent with each other: `layout` entries name
// coordination scopes that must exist in `coordinationSpace`, and Vitessce
// rewrites both when it upgrades a config (1.0.16 → 1.0.18). Laying a stored
// `layout` over a freshly prepared config therefore points every view at a
// scope that is not there — "A view-level error occurred.", three times.
// Live viewport-to-viewport sync is unaffected: it arrives through
// adoptCommit, not through the boot state.
const __FILE_KEYS = ["version", "description", "datasets", "initStrategy",
  "coordinationSpace", "layout"]
// What the desktop itself puts in a file-open state; everything else in it
// came from the caller and is theirs to keep.
const __FILE_STATE_KEYS = ['url', 'path', 'name', 'type']
async function __fromFile(state, lv) {
  if (typeof lv.call !== 'function') throw new Error('this pod has no app-backend support')
  const r = await lv.call('prepare', { path: state.path }, { timeoutMs: 600000 })
  if (!r || !r.config) throw new Error((r && r.error) || 'prepare returned no config')
  return r.config
}
export async function setup(lv, root) {
  const __cbs = []
  let __lastFile = null
  let __cur = null
  const wrapped = Object.create(lv)
  // Adapters read lv.state on their own re-renders (Vitessce does on window
  // resize). The SDK's store still holds the RAW state — file-shaped, or
  // stale after menu-driven changes that bypass it — so point the accessor
  // at what the adapter actually saw last.
  Object.defineProperty(wrapped, 'state', { get: () => __cur })
  wrapped.onState = (cb) => {
    __cbs.push(cb)
    lv.onState((state, info) => {
      // A file open is a file open. This used to also require that the state
      // carried NONE of the viewer's own keys — but those keys are exactly
      // what this app declares as `sync` state, so the first time anyone
      // toggled a mode or picked a colour the window could never run its
      // backend `prepare` again. It then fed the raw file envelope to the
      // viewer: spatial3d fetched `_spatial.json` from inside an .h5ad (404),
      // Vitessce reported "Missing version" on an object that was never a
      // config. The mapping is also what re-mints served URLs, so skipping it
      // left those windows pointing at a dead tunnel after every restart.
      const fileShaped = !!(state && state.path && state.url)
      if (!fileShaped) { __cur = state; cb(state, info); return }
      __lastFile = state
      Promise.resolve(__fromFile(state, lv)).then((mapped) => {
        // Anything the caller asked for beyond the file itself — a layout, a
        // colour scheme, desktop_open(path=…, state={…}) — must survive the
        // mapping. Dropping it silently is why "open it radial" came out
        // linear and sent an agent hunting for a bug that was ours.
        // __FILE_KEYS belong to the FILE: they are what the mapping produces,
        // and they carry served URLs only the current pod can mint. Anything
        // else in the state — a layout, a camera, a colour scheme — is the
        // caller's or the session's, and rides on top.
        const extra = {}
        for (const k of Object.keys(state)) {
          if (!__FILE_STATE_KEYS.includes(k) && !__FILE_KEYS.includes(k)) extra[k] = state[k]
        }
        __emitToApp(Object.assign({}, mapped, extra), info)
      }).catch((e) =>
        lv.fail('Could not open ' + (state.name || state.path) + ': ' + ((e && e.message) || e)))
    })
  }
  // Every shim delivery goes through here — and through the SDK's own store.
  // Adapters build their next state from lv.state (mode toggles, sliders); a
  // delivery that bypassed the store left it holding the bare init `{}`, and
  // the first toolbar click re-rendered from nothing ("Provide state.url").
  const __emitToApp = (state, info) => {
    __cur = state
    if (typeof lv.setState === 'function') lv.setState(state)
    for (const cb of __cbs) cb(state, info || { reason: 'set' })
  }
  // Menu actions patch the CURRENT viewer state — the adapter re-renders the
  // way it would for any set.
  const __patch = (p) => {
    if (!__cur) throw new Error('nothing is loaded yet')
    __emitToApp(Object.assign({}, __cur, p))
  }
  void __patch
  // ── View-menu engine ──────────────────────────────────────────────────
  // A Vitessce window IS its config, so per-panel control is config surgery:
  // the View menu lists every panel type this data supports, checkmarked
  // against the live layout, and toggling edits layout/coordinationSpace.
  // __config tracks every state the adapter sees — emit echoes included, so
  // a panel the user closes inside Vitessce un-checks in the menu.
  const __COMPONENTS = [
    ['heatmap', 'Heatmap'],
    ['obsSets', 'Cell Sets'],
    ['obsSetSizes', 'Cell Set Sizes'],
    ['featureList', 'Gene List'],
    ['obsSetFeatureValueDistribution', 'Violin Plots'],
    ['featureValueHistogram', 'Histogram'],
    ['description', 'Description'],
    ['status', 'Status'],
  ]
  let __config = null
  const __isConfig = (s) => !!(s && s.datasets && s.layout)
  const __clone = (o) => JSON.parse(JSON.stringify(o))
  // Both file shapes: our generated configs carry options.obsEmbedding;
  // configs Vitessce emits back have been through its file expansion, where
  // each embedding is its own file entry with coordinationValues instead.
  function __fileEmbeddings(cfg) {
    const out = []
    for (const ds of cfg.datasets || []) {
      for (const f of ds.files || []) {
        for (const e of (f.options && f.options.obsEmbedding) || []) {
          if (e.embeddingType && !out.includes(e.embeddingType)) out.push(e.embeddingType)
        }
        const cv = f.coordinationValues
        if (cv && cv.embeddingType && !out.includes(cv.embeddingType)) out.push(cv.embeddingType)
      }
    }
    return out
  }
  // Sticky: an emitted config that hides its embeddings must not shrink the
  // menu — remember the richest answer seen.
  let __embList = []
  function __captureEmb(cfg) {
    const found = __fileEmbeddings(cfg)
    if (found.length) __embList = found // authoritative when present; emits keep the last answer
  }
  function __scatterScopes(cfg, type) {
    const types = ((cfg.coordinationSpace || {}).embeddingType) || {}
    return Object.keys(types).filter((k) => types[k] === type)
  }
  function __scatterOpen(cfg, type) {
    const scopes = __scatterScopes(cfg, type)
    return (cfg.layout || []).some((p) => p.component === 'scatterplot'
      && p.coordinationScopes && scopes.includes(p.coordinationScopes.embeddingType))
  }
  function __nextY(cfg) {
    let y = 0
    for (const p of cfg.layout || []) y = Math.max(y, (p.y || 0) + (p.h || 0))
    return y
  }
  // Vitessce sizes rows as height/totalRows: a layout totalling 8 rows fills
  // two-thirds of the window and one totalling 16 squeezes. Rescale to the
  // 12-row reference after every toggle so panels always fill the height.
  function __normalizeRows(layout) {
    let total = 0
    for (const p of layout) total = Math.max(total, (p.y || 0) + (p.h || 0))
    if (!total || total === 12) return
    const f = 12 / total
    for (const p of layout) {
      const y0 = Math.round((p.y || 0) * f)
      const y1 = Math.round(((p.y || 0) + (p.h || 2)) * f)
      p.y = y0
      p.h = Math.max(1, y1 - y0)
    }
    // Rounding drift compounds across repeated normalizations and leaves the
    // total at 10–11 rows — stretch the bottom row back to exactly 12.
    let rounded = 0
    for (const p of layout) rounded = Math.max(rounded, p.y + p.h)
    if (rounded !== 12) {
      for (const p of layout) if (p.y + p.h === rounded) p.h = Math.max(1, p.h + (12 - rounded))
    }
  }
  function __pushMenus() {
    if (!lv.window || typeof lv.window.setMenus !== 'function') return
    const cfg = __config
    const emb = [...__embList]
    if (!emb.includes('UMAP')) emb.unshift('UMAP') // offered even when absent: computed on demand
    const comps = cfg ? (cfg.layout || []).map((p) => p.component) : []
    const items = emb.map((t) => ({
      label: 'Scatterplot (' + t + ')',
      action: 'toggleView', args: { scatter: t },
      checked: !!cfg && __scatterOpen(cfg, t),
    }))
    items.push({ separator: true })
    for (const [comp, label] of __COMPONENTS) {
      items.push({ label, action: 'toggleView', args: { component: comp }, checked: comps.includes(comp) })
    }
    lv.window.setMenus([
      { label: 'Data', items: [
        { label: 'Load Example Data', action: 'loadExample' },
        { separator: true },
        { label: 'Compute UMAP', action: 'computeUmap' },
      ] },
      { label: 'View', items },
    ])
  }
  const __apply = (config) => {
    __config = config
    __captureEmb(config)
    __emitToApp(config)
    __pushMenus()
  }
  // Capture every state the adapter is handed (post-mapping), so the menu
  // mirrors demos, examples, agent patches and user edits alike.
  const __baseOnState = wrapped.onState
  wrapped.onState = (cb) => __baseOnState((state, info) => {
    if (__isConfig(state)) { __config = state; __captureEmb(state); __pushMenus() }
    cb(state, info)
  })
  if (typeof lv.defineAction === 'function') {
    lv.defineAction('toggleView', async (args) => {
      if (!__config) throw new Error('nothing is loaded yet')
      const cfg = __clone(__config)
      if (args && args.scatter) {
        const t = String(args.scatter)
        cfg.coordinationSpace = cfg.coordinationSpace || {}
        const types = (cfg.coordinationSpace.embeddingType = cfg.coordinationSpace.embeddingType || {})
        if (__scatterOpen(cfg, t)) {
          const scopes = __scatterScopes(cfg, t)
          cfg.layout = (cfg.layout || []).filter((p) => !(p.component === 'scatterplot'
            && p.coordinationScopes && scopes.includes(p.coordinationScopes.embeddingType)))
        } else {
          if (!__embList.includes(t)) {
            if (t !== 'UMAP') throw new Error('the file has no ' + t + ' embedding')
            if (!__lastFile) throw new Error('Open an .h5ad file first — the example is remote data.')
            const r = await lv.call('compute_umap', { path: __lastFile.path }, { timeoutMs: 600000 })
            if (!r || !r.config) throw new Error((r && r.error) || 'compute_umap failed')
            cfg.datasets = r.config.datasets // fresh store URL with the embedding; MY layout stays
          }
          let scope = __scatterScopes(cfg, t)[0]
          if (!scope) {
            scope = 'A'
            while (types[scope] !== undefined && types[scope] !== t) {
              scope = String.fromCharCode(scope.charCodeAt(0) + 1)
            }
            types[scope] = t
          }
          ;(cfg.layout = cfg.layout || []).push({
            component: 'scatterplot',
            coordinationScopes: { embeddingType: scope },
            x: 0, y: __nextY(cfg), w: 6, h: 6,
          })
        }
      } else if (args && args.component) {
        const comp = String(args.component)
        if ((cfg.layout || []).some((p) => p.component === comp)) {
          cfg.layout = cfg.layout.filter((p) => p.component !== comp)
        } else {
          ;(cfg.layout = cfg.layout || []).push({ component: comp, x: 6, y: __nextY(cfg), w: 6, h: 4 })
        }
      }
      __normalizeRows(cfg.layout || [])
      __apply(cfg)
      return 'ok'
    })
    lv.defineAction('computeUmap', async () => {
      if (!__lastFile) throw new Error('Open an .h5ad file from the desktop first.')
      const r = await lv.call('compute_umap', { path: __lastFile.path }, { timeoutMs: 600000 })
      if (!r || !r.config) throw new Error((r && r.error) || 'compute_umap returned no config')
      __apply(r.config)
      return 'UMAP ready'
    })
    lv.defineAction('loadExample', async () => {
      const r = await lv.call('example', {}, { timeoutMs: 120000 })
      if (!r || !r.config) throw new Error((r && r.error) || 'no example bundled')
      __apply(r.config)
      return 'example loaded'
    })
  }
  return __viewerSetup(wrapped, root)
}
