/**
 * Mol* (molstar) LiveView adapter — a viewer plugin for 3D molecular
 * structures (proteins, nucleic acids, complexes).
 *
 * Like every viewer it is an ordinary setup(lv, root) module loaded by the
 * generic host. Mol* ships as a self-contained UMD bundle + CSS; this
 * adapter injects them from a CDN and drives `molstar.Viewer`.
 *
 * LiveView "state" — provide exactly one source:
 *   {
 *     "pdbId": "1CBS",                     // an RCSB PDB entry
 *     "alphafold": "P00533",               // AlphaFold DB, by UniProt accession
 *     "url": "http://.../structure.cif",   // a structure file (e.g. served
 *                                          //   via serve_local_data)
 *     "format": "mmcif"                    // for `url`: "mmcif" | "pdb"
 *   }
 */

const MOLSTAR = 'https://unpkg.com/molstar@5.9.0/build/viewer/molstar'

/** Inject the Mol* UMD bundle + stylesheet once; resolve when ready. */
function loadMolstar() {
  return new Promise((resolve, reject) => {
    if (window.molstar && window.molstar.Viewer) {
      resolve()
      return
    }
    const css = document.createElement('link')
    css.rel = 'stylesheet'
    css.href = MOLSTAR + '.css'
    document.head.appendChild(css)
    const js = document.createElement('script')
    js.src = MOLSTAR + '.js'
    js.onload = () => resolve()
    js.onerror = () => reject(new Error('failed to load Mol* from the CDN'))
    document.head.appendChild(js)
  })
}

async function __viewerSetup(lv, root) {
  if (!root.id) root.id = 'molstar-root'
  root.style.position = 'relative'
  root.style.width = '100%'
  root.style.height = '100%'

  await loadMolstar()  // throws → app-host reports the failure

  const viewer = await window.molstar.Viewer.create(root.id, {
    layoutIsExpanded: false,
    layoutShowControls: false,
    layoutShowSequence: false,
    layoutShowLog: false,
    viewportShowExpand: true,
    viewportShowSelectionMode: false,
    pdbProvider: 'rcsb',
  })

  let loadedKey = null

  async function loadStructure(state) {
    const key = JSON.stringify([
      state.pdbId, state.alphafold, state.url, state.format,
    ])
    if (key === loadedKey) return  // already showing this structure

    // Replace any previously loaded structure.
    loadedKey = null
    try {
      if (viewer.plugin && typeof viewer.plugin.clear === 'function') {
        await viewer.plugin.clear()
      }
    } catch (e) { /* best-effort */ }

    if (state.alphafold) {
      // Mol* fetches the AlphaFold DB model and colours it by pLDDT.
      await viewer.loadAlphaFoldDb(state.alphafold)
    } else if (state.pdbId) {
      await viewer.loadPdb(String(state.pdbId).toLowerCase())
    } else if (state.url) {
      await viewer.loadStructureFromUrl(state.url, state.format || 'mmcif')
    }
    // Mol* task failures can be recorded on data cells without rejecting the
    // viewer promise. Verify that a structure was actually produced before
    // acknowledging the agent's request or caching this source as loaded.
    const failed = [...viewer.plugin.state.data.cells.values()].find((cell) => cell.status === 'error')
    if (failed) throw new Error(failed.errorText || 'The structure could not be loaded.')
    if (!viewer.plugin.managers.structure.hierarchy.current.structures.length) {
      throw new Error('The source did not produce a molecular structure.')
    }
    loadedKey = key
  }

  lv.onState((state, info) => {
    if (info && info.reason === 'emit') return
    if (!state || (!state.pdbId && !state.alphafold && !state.url)) {
      lv.fail('Mol*: state needs one of pdbId / alphafold / url.')
      return
    }
    return loadStructure(state).catch((e) =>
      lv.fail('Mol* failed to load the structure: ' + ((e && e.message) || e)),
    )
  })

  // Snapshot — use Mol*'s own screenshot helper. It handles the WebGL
  // drawing-buffer issues internally (a plain canvas.toDataURL would be
  // blank because Mol*'s context has preserveDrawingBuffer = false).
  lv.onSnapshot(async () => {
    try {
      const helper = viewer.plugin?.helpers?.viewportScreenshot
      if (helper && typeof helper.getImageDataUri === 'function') {
        const url = await helper.getImageDataUri()
        if (url) return url
      }
    } catch (e) { /* fall through to the raw-canvas attempt */ }
    const canvas = root.querySelector('canvas')
    if (!canvas) return null
    try {
      return canvas.toDataURL('image/jpeg', 0.85)
    } catch (e) {
      return null  // fall back to the host's html2canvas
    }
  })
}


// ── file-open shim (generated by convert-viewers.py) ─────────────────────────
// The desktop opens files with generic state {url, path, name, type}; the
// viewer's own contract is documented at the top of this file. File-shaped
// state (a `path`, none of the viewer's keys) is mapped before the stock
// adapter sees it; everything else — agent states, demos — passes through.
const __FILE_KEYS = ["pdbId", "alphafold", "format"]
// What the desktop itself puts in a file-open state; everything else in it
// came from the caller and is theirs to keep.
const __FILE_STATE_KEYS = ['url', 'path', 'name', 'type']
async function __fromFile(state) {
  const lower = String(state.name || state.path).toLowerCase()
  return { url: state.url, format: lower.endsWith('.pdb') ? 'pdb' : 'mmcif' }
}
export async function setup(lv, root) {
  const __cbs = []
  let __publishing = false
  let __lastFile = null
  let __cur = null
  const wrapped = Object.create(lv)
  // Adapters read lv.state on their own re-renders (Vitessce does on window
  // resize). The SDK's store still holds the RAW state — file-shaped, or
  // stale after menu-driven changes that bypass it — so point the accessor
  // at what the adapter actually saw last.
  Object.defineProperty(wrapped, 'state', { get: () => __cur })
  wrapped.onState = (cb) => {
    __cbs.push(cb)
    lv.onState((state, info) => {
      if (__publishing) return
      // A file open is a file open. This used to also require that the state
      // carried NONE of the viewer's own keys — but those keys are exactly
      // what this app declares as `sync` state, so the first time anyone
      // toggled a mode or picked a colour the window could never run its
      // backend `prepare` again. It then fed the raw file envelope to the
      // viewer: spatial3d fetched `_spatial.json` from inside an .h5ad (404),
      // Vitessce reported "Missing version" on an object that was never a
      // config. The mapping is also what re-mints served URLs, so skipping it
      // left those windows pointing at a dead tunnel after every restart.
      const fileShaped = !!(state && state.path && state.url)
      if (!fileShaped) { __cur = state; return cb(state, info) }
      __lastFile = state
      return Promise.resolve(__fromFile(state, lv)).then((mapped) => {
        // Anything the caller asked for beyond the file itself — a layout, a
        // colour scheme, desktop_open(path=…, state={…}) — must survive the
        // mapping. Dropping it silently is why "open it radial" came out
        // linear and sent an agent hunting for a bug that was ours.
        // __FILE_KEYS belong to the FILE: they are what the mapping produces,
        // and they carry served URLs only the current pod can mint. Anything
        // else in the state — a layout, a camera, a colour scheme — is the
        // caller's or the session's, and rides on top.
        const extra = {}
        for (const k of Object.keys(state)) {
          if (!__FILE_STATE_KEYS.includes(k) && !__FILE_KEYS.includes(k)) extra[k] = state[k]
        }
        return __emitToApp(Object.assign({}, mapped, extra), info)
      }).catch((e) =>
        lv.fail('Could not open ' + (state.name || state.path) + ': ' + ((e && e.message) || e)))
    })
  }
  // Every shim delivery goes through here — and through the SDK's own store.
  // Adapters build their next state from lv.state (mode toggles, sliders); a
  // delivery that bypassed the store left it holding the bare init `{}`, and
  // the first toolbar click re-rendered from nothing ("Provide state.url").
  const __emitToApp = async (state, info) => {
    __cur = state
    for (const cb of __cbs) await cb(state, info || { reason: 'set' })
    // Publish the canonical viewer state exactly once. A merge would keep
    // the original file envelope and rerun prepare on the next UI change.
    // SDK emitState calls onState synchronously; suppress that echo because
    // the renderer above already completed. The SDK's fluent API is not a promise.
    __publishing = true
    try {
      if (typeof lv.emitState === 'function') lv.emitState(state)
      else if (typeof lv.setState === 'function') lv.setState(state)
    } finally { __publishing = false }
  }
  // Menu actions patch the CURRENT viewer state — the adapter re-renders the
  // way it would for any set.
  const __patch = (p) => {
    if (!__cur) throw new Error('nothing is loaded yet')
    return __emitToApp(Object.assign({}, __cur, p))
  }
  void __patch
  return __viewerSetup(wrapped, root)
}
